### ISSUE TITLE
GPL-3.0 is incompatible with Minecraft

### ISSUE THREAD

**Issue by verarr** [eclipseisoffline/customtimecycle#3]
Minecraft is nonfree software, which the GPL-3.0 license does not allow linking with. (or, even if this isn't 100% true or applicable to this mod, it may cause some issues)

Instead, some suggestions are:
- [LGPL-3.0](https://choosealicense.com/licenses/lgpl-3.0/)
- [OSL-3.0](https://opensource.org/license/osl-3-0-php)
- [MPL-2.0](https://choosealicense.com/licenses/mpl-2.0/)
- [MIT](https://choosealicense.com/licenses/mit/) (permissive, you may want to avoid)

It seems like there are no other contributors to this source code (yet) so relicensing should be easy.

**Comment by eclipseisoffline** [comment]
Hi, apologies for the late reply, I've been pretty busy lately meaning I had less time available for programming.

Thanks for pointing this out! I've relicensed this project under LGPL-3.0 and will do the same for my other projects when I get to updating them.
