### ISSUE TITLE
Day counter is stuck at 0

### ISSUE THREAD

**Issue by kutaxoff** [eclipseisoffline/customtimecycle#6]
With the mod the day counter (in F3 menu or by `time query day` command) is 0 regardless of which numbers to pass to the `time set` or `time add` commands. Some mods that show the day counter somehow are affected by this

**Comment by eclipseisoffline** [comment]
Hi, this has been fixed in #4, which will be included in the next release for 1.21/1.21.2, hopefully in a couple of days.
